name: Build Angular Project

# This workflow is triggered on pushes and pull requests to the src directory
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version here
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - name: List directory structure
        run: |
          pwd
          ls -l
          # List contents of src if needed
          ls -l src

      - name: Install Dependencies
        run: |
          npm install
          
      - name: Build Angular App
        run: |
          cd src/app
          ng build --configuration=production
